//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shilenko_wpf1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutobaseEntities : DbContext
    {
        public AutobaseEntities()
            : base("name=AutobaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EmployeePositions> EmployeePositions { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<TripStatuses> TripStatuses { get; set; }
        public virtual DbSet<TripTimes> TripTimes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VehicleStatuses> VehicleStatuses { get; set; }
        public virtual DbSet<Waybills> Waybills { get; set; }
    }
}
