//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shilenko_wpf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trips()
        {
            this.Orders = new HashSet<Orders>();
            this.Waybills = new HashSet<Waybills>();
        }
    
        public int TripID { get; set; }
        public int RouteID { get; set; }
        public int CarID { get; set; }
        public int DriverID { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.TimeSpan> ActualDeparture { get; set; }
        public Nullable<System.TimeSpan> ActualArrival { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Drivers Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Routes Routes { get; set; }
        public virtual TripStatuses TripStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waybills> Waybills { get; set; }
    }
}
