//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shilenko_wpf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybills
    {
        public int WaybillID { get; set; }
        public int TripID { get; set; }
        public int DriverID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int StartMileage { get; set; }
        public Nullable<int> EndMileage { get; set; }
        public Nullable<decimal> FuelConsumption { get; set; }
        public string Notes { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
